// lib/product_data.dart

class ProductData {
  static final List<Map<String, dynamic>> menuBakery = [
    {
      "name": "Dark Cocoa Dream",
      "price": 240000.0,
      "rating": 4.9,
      "ratingCount": 128,
      "tag": "Terlaris",
      "category": "Kue Tart",
      "desc": "Kue tart cokelat murni berlapis krim cokelat Belgia yang sangat lumer dan manisnya pas.",
      "image": "assets/images/dark_cocoa.jpg",
    },
    {
      "name": "Strawberry Chiffon",
      "price": 285000.0,
      "rating": 4.8,
      "ratingCount": 95,
      "tag": "Populer",
      "category": "Kue Tart",
      "desc": "Kue sifon yang sangat lembut dengan balutan krim vanila dan buah stroberi segar di atasnya.",
      "image": "assets/images/strawberry_chiffon.jpg",
    },
    {
      "name": "Matcha Crepe Cake",
      "price": 320000.0,
      "rating": 4.7,
      "ratingCount": 74,
      "tag": "Rekomendasi",
      "category": "Kue Tart",
      "desc": "Lapisan crepe tipis legendaris dengan olesan krim teh hijau Jepang asli yang harum.",
      "image": "assets/images/matcha_crepe.jpg",
    },
    {
      "name": "Hibiscus Glaze Donut",
      "price": 37500.0,
      "rating": 4.7,
      "ratingCount": 210,
      "tag": "Populer",
      "category": "Donat",
      "desc": "Donat kentang empuk dengan lapisan gula glaze rasa bunga hibiscus yang manis dan segar.",
      "image": "assets/images/hibiscus_donut.jpg",
    },
    {
      "name": "Almond Snow Donut",
      "price": 40000.0,
      "rating": 4.8,
      "ratingCount": 89,
      "tag": "Baru",
      "category": "Donat",
      "desc": "Donat dengan taburan kacang almond panggang renyah dan taburan gula putih halus.",
      "image": "assets/images/almond_snow.jpg",
    },
    {
      "name": "Choco Caviar Donut",
      "price": 42500.0,
      "rating": 4.9,
      "ratingCount": 312,
      "tag": "Terlaris",
      "category": "Donat",
      "desc": "Donat bomboloni isi cokelat lumer padat dengan toping bola-bola cokelat renyah di atasnya.",
      "image": "assets/images/choco_caviar.jpg",
    },
    {
      "name": "Butter Croissant",
      "price": 45000.0,
      "rating": 4.8,
      "ratingCount": 176,
      "tag": "Segar dari Oven",
      "category": "Croissant",
      "desc": "Roti croissant klasik Perancis yang super renyah di luar namun sangat lembut di dalam.",
      "image": "assets/images/butter_croissant.jpg",
    },
    {
      "name": "Almond Croissant",
      "price": 55000.0,
      "rating": 4.9,
      "ratingCount": 143,
      "tag": "Rekomendasi",
      "category": "Croissant",
      "desc": "Croissant gurih yang diisi dengan krim almond manis melimpah dan taburan irisan almond.",
      "image": "assets/images/almond_croissant.jpg",
    },
  ];
}